title = "Elite"
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

  # [languages.en.taxonomies]
  # category = "categories"
  # tag = "tags"
  # series = "series"

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

# [[languages.en.menu.main]]
# name = "Tags"
# url = "tags/"
# weight = 10

# [languages.fr]
# languageName = ":fr:"
# weight = 2
# title = "PaperModL2"
#
#   [languages.fr.taxonomies]
#   category = "FRcategories"
#   tag = "FRtags"
#   series = "FRseries"
#
# [[languages.fr.menu.main]]
# name = "Archive"
# url = "archives/"
# weight = 5
#
# [[languages.fr.menu.main]]
# name = "FRTags"
# url = "frtags"
# weight = 10
#
# [[languages.fr.menu.main]]
# name = "FRCategories"
# url = "frcategories"
# weight = 10
#
# [[languages.fr.menu.main]]
# name = "FRSeries"
# url = "frseries"
# weight = 10
#
# [[languages.fr.menu.main]]
# name = "NullLink"
# url = "#"
#
#   [languages.fr.params]
#   languageAltTitle = "French"
#
#     [languages.fr.params.profileMode]
#     enabled = true
#     title = "PaperMod"
#     imageUrl = "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
#     imageTitle = "ProfileMode image"
#     subtitle = "â˜„ï¸ Fast | â˜ï¸ Fluent | ğŸŒ™ Smooth | ğŸ“± Responsive"
#
#       [[languages.fr.params.profileMode.buttons]]
#       name = "Blog"
#       url = "posts"
#
#       [[languages.fr.params.profileMode.buttons]]
#       name = "Profile Mode"
#       url = "https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode"
#
# [languages.ara]
# languagedirection = "rtl"
# weight = 3
# title = "Ø§Ù„ØªØ¹Ù„ÙŠÙ… Ø§Ù„Ø±Ù‚Ù…ÙŠ"
#
#   # [languages.ara.taxonomies]
#   # category = "FAcategories"
#   # tag = "FAtags"
#   # series = "FAseries"
#
# [[languages.ara.menu.main]]
# name = "Ø§Ù„Ø¨Ø­Ø«"
# url = "search/"
# weight = 10
#
# [languages.ara.params.homeInfoParams]
# Title = "Ø§Ù„Ø³Ù„Ø§Ù… Ø¹Ù„ÙŠÙƒÙ…"
# Content = "Welcome to RTL layout"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
# env = "production"
defaultTheme = "auto"
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
# ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
# images = [ "images/papermod-cover.png" ]
#
#   [params.profileMode]
#   enabled = false
#   title = "PaperMod"
#   imageUrl = "#"
#   imageTitle = "my image"
#
#     [[params.profileMode.buttons]]
#     name = "Archives"
#     url = "archives"
#
#     [[params.profileMode.buttons]]
#     name = "Tags"
#     url = "tags"
#
  [params.homeInfoParams]
  Title = "Programming with Python"
  Content = """
ğŸ‘‹ Welcome to our Project!
"""

  # [params.editPost]
  # URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  # Text = "Suggest Changes"
  # appendFilePath = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
